<script setup>
definePage({
  meta: {
    title: 'Special homepage — Create account',
    description: 'Account creation page reached from the Special homepage user menu — the v3-alt signup flow with autogenerated usernames. Ctrl+Shift+S opens the admin panel; ?variant=v1 picks a variant.',
  },
})

import { ref, provide, onMounted, onUnmounted } from 'vue'
import MobileWrapper from '@/components/MobileWrapper.vue'
import CreateAccountView from './views/CreateAccountView.vue'
import AdminPanel from './components/AdminPanel.vue'
import './styles/global.css'

const showAdmin = ref(false)

function toggleAdmin() {
  showAdmin.value = !showAdmin.value
}

provide('toggleAdmin', toggleAdmin)

function onKeydown(e) {
  if (e.ctrlKey && e.shiftKey && e.key === 'S') {
    e.preventDefault()
    toggleAdmin()
  }
}

onMounted(() => window.addEventListener('keydown', onKeydown))
onUnmounted(() => window.removeEventListener('keydown', onKeydown))
</script>

<template>
  <MobileWrapper max-width="480px">
    <CreateAccountView />
  </MobileWrapper>
  <AdminPanel v-if="showAdmin" @close="showAdmin = false" />
</template>
